sudo: required
dist: trusty
before_install:
install:
before_script:
script:
  - ./package.sh ${DISTRIBUTIONS} ${ARCHITECTURES}
after_failure:
after_success:
env:
  matrix:
    - DISTRIBUTIONS=trusty ARCHITECTURES=i386
    - DISTRIBUTIONS=xenial ARCHITECTURES=i386
    - DISTRIBUTIONS=trusty ARCHITECTURES=amd64
    - DISTRIBUTIONS=xenial ARCHITECTURES=amd64
